### ISSUE TITLE
Issue with HA update 2024.06

### ISSUE THREAD

**Issue by DanieleNeo** [richardzone/homeassistant-dht#133]
I don't know if it's an dht issue but after updating HA to last release dht is not working and I have these in the log

```
2024-06-22 01:18:23.096 ERROR (SyncWorker_6) [homeassistant.util.package] Unable to install package adafruit-circuitpython-dht==3.7.0: error: subprocess-exited-with-error
× python setup.py bdist_wheel did not run successfully.
│ exit code: 1
╰─> [15 lines of output]
******************************************************************************
* Setup can't determine the value of PAGE_SIZE on your system, so it will
* default to 4096 which may not be correct.
*
* Please report this message and your operating system info to the package
* maintainer listed in the README file.
******************************************************************************
running bdist_wheel
running build
running build_ext
building 'sysv_ipc' extension
creating build
creating build/temp.linux-aarch64-cpython-312
gcc -fno-strict-overflow -Wsign-compare -DNDEBUG -g -O3 -Wall -fno-semantic-interposition -fno-builtin-malloc -fno-builtin-calloc -fno-builtin-realloc -fno-builtin-free -DTHREAD_STACK_SIZE=0x100000 -fPIC -I/usr/local/include/python3.12 -c common.c -o build/temp.linux-aarch64-cpython-312/common.o
error: command 'gcc' failed: No such file or directory
[end of output]
note: This error originates from a subprocess, and is likely not a problem with pip.
```

Thanks
D.

**Comment by fer4droid** [comment]
I have the same issue since yesterday.

**Comment by 599316527** [comment]
I have the same issue.

```
Platform error 'sensor' from integration 'dht' - Requirements for dht not found: ['adafruit-circuitpython-dht==3.7.0'].
```

```
Core               2024.6.4
Supervisor         2024.06.0
Operating System   12.4
Frontend           20240610.1
```

**Comment by bilguun0203** [comment]
I had the same problem and fixed it by installing `gcc`, `musl-dev`, and `linux-headers` in the `homeassistant` container.

1. [SSH into HA](https://developers.home-assistant.io/docs/operating-system/debugging/)
2. Install necessary packages `docker exec homeassistant apk add gcc musl-dev linux-headers` (Edit: updated command `docker exec homeassistant apk add build-base`)
3. (Optional) If you are using Raspberry Pi, add the `use_pulseio=False` parameter to the initialization of the DHT sensor in [`sensor.py` at line 191](https://github.com/bilguun0203/homeassistant-dht/commit/eed5ddf55405abce271bf09b697ad600c06aa2fd#diff-28663e7f53a05342e575e0f78d8521877460051e41b6aac47f81df544a0c343fL191-R191).
4. Restart HA

**Comment by DanieleNeo** [comment]
> I had the same problem and fixed it by installing `gcc`, `musl-dev`, and `linux-headers` in the `homeassistant` container.
> 
> 1. [SSH into HA](https://developers.home-assistant.io/docs/operating-system/debugging/)
> 2. Install necessary packages `docker exec homeassistant apk add gcc musl-dev linux-headers`
> 3. (Optional) If you are using Raspberry Pi, add the `use_pulseio=False` parameter to the initialization of the DHT sensor in [`sensor.py` at line 191](https://github.com/bilguun0203/homeassistant-dht/commit/eed5ddf55405abce271bf09b697ad600c06aa2fd#diff-28663e7f53a05342e575e0f78d8521877460051e41b6aac47f81df544a0c343fL191-R191).
> 4. Restart HA

Hi @bilguun0203,

thanks for your solution but I'm using HAOS, and I think that this is not working for me. I tried docker exec homeassistant apk add gcc musl-dev linux-headers, but I got "docker command not found".

D.

**Comment by stegno** [comment]
The same issue. Unfortunately integration doesn't work nomore...

**Comment by stegno** [comment]
> I had the same problem and fixed it by installing `gcc`, `musl-dev`, and `linux-headers` in the `homeassistant` container.
> 
> 1. [SSH into HA](https://developers.home-assistant.io/docs/operating-system/debugging/)
> 2. Install necessary packages `docker exec homeassistant apk add gcc musl-dev linux-headers`
> 3. (Optional) If you are using Raspberry Pi, add the `use_pulseio=False` parameter to the initialization of the DHT sensor in [`sensor.py` at line 191](https://github.com/bilguun0203/homeassistant-dht/commit/eed5ddf55405abce271bf09b697ad600c06aa2fd#diff-28663e7f53a05342e575e0f78d8521877460051e41b6aac47f81df544a0c343fL191-R191).
> 4. Restart HA

I made it, but it did not resolve the issue. Using HAOS.

**Comment by bilguun0203** [comment]
> > I had the same problem and fixed it by installing `gcc`, `musl-dev`, and `linux-headers` in the `homeassistant` container.
> > 
> > 1. [SSH into HA](https://developers.home-assistant.io/docs/operating-system/debugging/)
> > 2. Install necessary packages `docker exec homeassistant apk add gcc musl-dev linux-headers`
> > 3. (Optional) If you are using Raspberry Pi, add the `use_pulseio=False` parameter to the initialization of the DHT sensor in [`sensor.py` at line 191](https://github.com/bilguun0203/homeassistant-dht/commit/eed5ddf55405abce271bf09b697ad600c06aa2fd#diff-28663e7f53a05342e575e0f78d8521877460051e41b6aac47f81df544a0c343fL191-R191).
> > 4. Restart HA
> 
> I made it, but it did not resolve the issue. Using HAOS.

Can you show me the error log related to dht from home assistant logs?

If it's related to installing the `sysv_ipc` package (which has happened to me since the last home assistant update), the workaround I currently use is to download and extract the source ([sysv_ipc-1.1.0.tar.gz](https://files.pythonhosted.org/packages/0c/d7/5d2f861155e9749f981e6c58f2a482d3ab458bf8c35ae24d4b4d5899ebf9/sysv_ipc-1.1.0.tar.gz)) to the `homeassistant` container and install it manually by using `python setup.py install` command inside the container. (https://github.com/osvenskan/sysv_ipc/issues/6)

```
Core			2024.7.3
Supervisor		2024.06.2
Operating System	12.4
Frontend		20240710.0
```

**Comment by bilguun0203** [comment]
> > I had the same problem and fixed it by installing `gcc`, `musl-dev`, and `linux-headers` in the `homeassistant` container.
> > 
> > 1. [SSH into HA](https://developers.home-assistant.io/docs/operating-system/debugging/)
> > 2. Install necessary packages `docker exec homeassistant apk add gcc musl-dev linux-headers`
> > 3. (Optional) If you are using Raspberry Pi, add the `use_pulseio=False` parameter to the initialization of the DHT sensor in [`sensor.py` at line 191](https://github.com/bilguun0203/homeassistant-dht/commit/eed5ddf55405abce271bf09b697ad600c06aa2fd#diff-28663e7f53a05342e575e0f78d8521877460051e41b6aac47f81df544a0c343fL191-R191).
> > 4. Restart HA
> 
> Hi @bilguun0203,
> 
> thanks for your solution but I'm using HAOS, and I think that this is not working for me. I tried docker exec homeassistant apk add gcc musl-dev linux-headers, but I got "docker command not found".
> 
> D.

Sorry for the late reply. I'm using HAOS as well, and the `docker` command runs fine. Did you ssh directly into HAOS using port 22222?

Here is mine:

![image](https://github.com/user-attachments/assets/7d8a6d35-c670-4cc5-ae46-ad1e7329a662)

**Comment by stegno** [comment]
Did anyone find some solution?

Tried to roll-back to previous HA core versions and it did not work for me unfortunately..

**Comment by Pavel-Demidyuk** [comment]
> > > I had the same problem and fixed it by installing `gcc`, `musl-dev`, and `linux-headers` in the `homeassistant` container.
> > > 
> > > 1. [SSH into HA](https://developers.home-assistant.io/docs/operating-system/debugging/)
> > > 2. Install necessary packages `docker exec homeassistant apk add gcc musl-dev linux-headers`
> > > 3. (Optional) If you are using Raspberry Pi, add the `use_pulseio=False` parameter to the initialization of the DHT sensor in [`sensor.py` at line 191](https://github.com/bilguun0203/homeassistant-dht/commit/eed5ddf55405abce271bf09b697ad600c06aa2fd#diff-28663e7f53a05342e575e0f78d8521877460051e41b6aac47f81df544a0c343fL191-R191).
> > > 4. Restart HA
> > 
> > 
> > Hi @bilguun0203,
> > thanks for your solution but I'm using HAOS, and I think that this is not working for me. I tried docker exec homeassistant apk add gcc musl-dev linux-headers, but I got "docker command not found".
> > D.
> 
> Sorry for the late reply. I'm using HAOS as well, and the `docker` command runs fine. Did you ssh directly into HAOS using port 22222?
> 
> Here is mine:
> 
> ![image](https://private-user-images.githubusercontent.com/8552387/350957101-7d8a6d35-c670-4cc5-ae46-ad1e7329a662.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzODI4NzYsIm5iZiI6MTcyMzM4MjU3NiwicGF0aCI6Ii84NTUyMzg3LzM1MDk1NzEwMS03ZDhhNmQzNS1jNjcwLTRjYzUtYWU0Ni1hZDFlNzMyOWE2NjIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTFUMTMyMjU2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjUzNTUwZmUyNmE2YTIyYmJiZThmOGNmZmZiNTBjYWU3OGE0MTk1MTUzMzU2MGU4NDM3ZjJlNWQ0OWIyM2RkZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Toj_qtnvcfNffz_15tz9FFnqRmswtriwuCWcq_uuUbk)

I'm using HAOS, and I'm able to ssh to 22222 port and run docker there, but "apk add gcc musl-dev linux-header" does nothing - still getting same errors:


```
Unable to install package adafruit-circuitpython-dht==3.7.0: error: subprocess-exited-with-error × python setup.py egg_info did not run successfully. │ exit code: 1 ╰─> [19 lines of output] Traceback (most recent call last): File "<string>", line 2, in <module> File "<pip-setuptools-caller>", line 34, in <module> File "/tmp/pip-install-9on0ybas/sysv-ipc_a5a6d61af134454eaa4f6398e7bb9220/setup.py", line 40, in <module> prober.probe() File "/tmp/pip-install-9on0ybas/sysv-ipc_a5a6d61af134454eaa4f6398e7bb9220/prober.py", line 138, in probe d["PAGE_SIZE"] = probe_page_size() ^^^^^^^^^^^^^^^^^ File "/tmp/pip-install-9on0ybas/sysv-ipc_a5a6d61af134454eaa4f6398e7bb9220/prober.py", line 111, in probe_page_size page_size = compile_and_run("probe_page_size.c") ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/tmp/pip-install-9on0ybas/sysv-ipc_a5a6d61af134454eaa4f6398e7bb9220/prober.py", line 82, in compile_and_run s = subprocess.Popen(["./prober/foo"], ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/subprocess.py", line 1026, in __init__ self._execute_child(args, executable, preexec_fn, close_fds, File "/usr/local/lib/python3.12/subprocess.py", line 1955, in _execute_child raise child_exception_type(errno_num, err_msg, err_filename) PermissionError: [Errno 13] Permission denied: './prober/foo' [end of output] note: This error originates from a subprocess, and is likely not a problem with pip. error: metadata-generation-failed × Encountered error while generating package metadata. ╰─> See above for output. note: This is an issue with the package mentioned above, not pip. hint: See above for details.
```

**Comment by DanieleNeo** [comment]
> > > > I had the same problem and fixed it by installing `gcc`, `musl-dev`, and `linux-headers` in the `homeassistant` container.
> > > > 
> > > > 1. [SSH into HA](https://developers.home-assistant.io/docs/operating-system/debugging/)
> > > > 2. Install necessary packages `docker exec homeassistant apk add gcc musl-dev linux-headers`
> > > > 3. (Optional) If you are using Raspberry Pi, add the `use_pulseio=False` parameter to the initialization of the DHT sensor in [`sensor.py` at line 191](https://github.com/bilguun0203/homeassistant-dht/commit/eed5ddf55405abce271bf09b697ad600c06aa2fd#diff-28663e7f53a05342e575e0f78d8521877460051e41b6aac47f81df544a0c343fL191-R191).
> > > > 4. Restart HA
> > > 
> > > 
> > > Hi @bilguun0203,
> > > thanks for your solution but I'm using HAOS, and I think that this is not working for me. I tried docker exec homeassistant apk add gcc musl-dev linux-headers, but I got "docker command not found".
> > > D.
> > 
> > 
> > Sorry for the late reply. I'm using HAOS as well, and the `docker` command runs fine. Did you ssh directly into HAOS using port 22222?
> > Here is mine:
> > ![image](https://private-user-images.githubusercontent.com/8552387/350957101-7d8a6d35-c670-4cc5-ae46-ad1e7329a662.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzODI4NzYsIm5iZiI6MTcyMzM4MjU3NiwicGF0aCI6Ii84NTUyMzg3LzM1MDk1NzEwMS03ZDhhNmQzNS1jNjcwLTRjYzUtYWU0Ni1hZDFlNzMyOWE2NjIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTFUMTMyMjU2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjUzNTUwZmUyNmE2YTIyYmJiZThmOGNmZmZiNTBjYWU3OGE0MTk1MTUzMzU2MGU4NDM3ZjJlNWQ0OWIyM2RkZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Toj_qtnvcfNffz_15tz9FFnqRmswtriwuCWcq_uuUbk)
> 
> I'm using HAOS, and I'm able to ssh to 22222 port and run docker there, but "apk add gcc musl-dev linux-header" does nothing - still getting same errors:
> 
> ```
> Unable to install package adafruit-circuitpython-dht==3.7.0: error: subprocess-exited-with-error × python setup.py egg_info did not run successfully. │ exit code: 1 ╰─> [19 lines of output] Traceback (most recent call last): File "<string>", line 2, in <module> File "<pip-setuptools-caller>", line 34, in <module> File "/tmp/pip-install-9on0ybas/sysv-ipc_a5a6d61af134454eaa4f6398e7bb9220/setup.py", line 40, in <module> prober.probe() File "/tmp/pip-install-9on0ybas/sysv-ipc_a5a6d61af134454eaa4f6398e7bb9220/prober.py", line 138, in probe d["PAGE_SIZE"] = probe_page_size() ^^^^^^^^^^^^^^^^^ File "/tmp/pip-install-9on0ybas/sysv-ipc_a5a6d61af134454eaa4f6398e7bb9220/prober.py", line 111, in probe_page_size page_size = compile_and_run("probe_page_size.c") ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/tmp/pip-install-9on0ybas/sysv-ipc_a5a6d61af134454eaa4f6398e7bb9220/prober.py", line 82, in compile_and_run s = subprocess.Popen(["./prober/foo"], ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/subprocess.py", line 1026, in __init__ self._execute_child(args, executable, preexec_fn, close_fds, File "/usr/local/lib/python3.12/subprocess.py", line 1955, in _execute_child raise child_exception_type(errno_num, err_msg, err_filename) PermissionError: [Errno 13] Permission denied: './prober/foo' [end of output] note: This error originates from a subprocess, and is likely not a problem with pip. error: metadata-generation-failed × Encountered error while generating package metadata. ╰─> See above for output. note: This is an issue with the package mentioned above, not pip. hint: See above for details.
> ```

Same problem for me

`Registratore: homeassistant.util.package
Fonte: util/package.py:123
Prima occorrenza: 21:57:57 (3 occorrenze)
Ultima registrazione: 21:58:40

Unable to install package adafruit-circuitpython-dht==3.7.0: error: subprocess-exited-with-error × python setup.py egg_info did not run successfully. │ exit code: 1 ╰─> [19 lines of output] Traceback (most recent call last): File "<string>", line 2, in <module> File "<pip-setuptools-caller>", line 34, in <module> File "/tmp/pip-install-56t85bk2/sysv-ipc_dcf2ff3c836d45e19aad7eb7e60adfb3/setup.py", line 40, in <module> prober.probe() File "/tmp/pip-install-56t85bk2/sysv-ipc_dcf2ff3c836d45e19aad7eb7e60adfb3/prober.py", line 138, in probe d["PAGE_SIZE"] = probe_page_size() ^^^^^^^^^^^^^^^^^ File "/tmp/pip-install-56t85bk2/sysv-ipc_dcf2ff3c836d45e19aad7eb7e60adfb3/prober.py", line 111, in probe_page_size page_size = compile_and_run("probe_page_size.c") ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/tmp/pip-install-56t85bk2/sysv-ipc_dcf2ff3c836d45e19aad7eb7e60adfb3/prober.py", line 82, in compile_and_run s = subprocess.Popen(["./prober/foo"], ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/subprocess.py", line 1026, in __init__ self._execute_child(args, executable, preexec_fn, close_fds, File "/usr/local/lib/python3.12/subprocess.py", line 1955, in _execute_child raise child_exception_type(errno_num, err_msg, err_filename) PermissionError: [Errno 13] Permission denied: './prober/foo' [end of output] note: This error originates from a subprocess, and is likely not a problem with pip. error: metadata-generation-failed × Encountered error while generating package metadata. ╰─> See above for output. note: This is an issue with the package mentioned above, not pip. hint: See above for details.
Unable to install package adafruit-circuitpython-dht==3.7.0: error: subprocess-exited-with-error × python setup.py egg_info did not run successfully. │ exit code: 1 ╰─> [19 lines of output] Traceback (most recent call last): File "<string>", line 2, in <module> File "<pip-setuptools-caller>", line 34, in <module> File "/tmp/pip-install-2mo8mrna/sysv-ipc_c6d3c3dddcaa4812bbe32bf72c64bb43/setup.py", line 40, in <module> prober.probe() File "/tmp/pip-install-2mo8mrna/sysv-ipc_c6d3c3dddcaa4812bbe32bf72c64bb43/prober.py", line 138, in probe d["PAGE_SIZE"] = probe_page_size() ^^^^^^^^^^^^^^^^^ File "/tmp/pip-install-2mo8mrna/sysv-ipc_c6d3c3dddcaa4812bbe32bf72c64bb43/prober.py", line 111, in probe_page_size page_size = compile_and_run("probe_page_size.c") ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/tmp/pip-install-2mo8mrna/sysv-ipc_c6d3c3dddcaa4812bbe32bf72c64bb43/prober.py", line 82, in compile_and_run s = subprocess.Popen(["./prober/foo"], ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/subprocess.py", line 1026, in __init__ self._execute_child(args, executable, preexec_fn, close_fds, File "/usr/local/lib/python3.12/subprocess.py", line 1955, in _execute_child raise child_exception_type(errno_num, err_msg, err_filename) PermissionError: [Errno 13] Permission denied: './prober/foo' [end of output] note: This error originates from a subprocess, and is likely not a problem with pip. error: metadata-generation-failed × Encountered error while generating package metadata. ╰─> See above for output. note: This is an issue with the package mentioned above, not pip. hint: See above for details.
Unable to install package adafruit-circuitpython-dht==3.7.0: error: subprocess-exited-with-error × python setup.py egg_info did not run successfully. │ exit code: 1 ╰─> [19 lines of output] Traceback (most recent call last): File "<string>", line 2, in <module> File "<pip-setuptools-caller>", line 34, in <module> File "/tmp/pip-install-om_x4a0d/sysv-ipc_2c63fe8f949740e3852e3d3c576ed071/setup.py", line 40, in <module> prober.probe() File "/tmp/pip-install-om_x4a0d/sysv-ipc_2c63fe8f949740e3852e3d3c576ed071/prober.py", line 138, in probe d["PAGE_SIZE"] = probe_page_size() ^^^^^^^^^^^^^^^^^ File "/tmp/pip-install-om_x4a0d/sysv-ipc_2c63fe8f949740e3852e3d3c576ed071/prober.py", line 111, in probe_page_size page_size = compile_and_run("probe_page_size.c") ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/tmp/pip-install-om_x4a0d/sysv-ipc_2c63fe8f949740e3852e3d3c576ed071/prober.py", line 82, in compile_and_run s = subprocess.Popen(["./prober/foo"], ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/subprocess.py", line 1026, in __init__ self._execute_child(args, executable, preexec_fn, close_fds, File "/usr/local/lib/python3.12/subprocess.py", line 1955, in _execute_child raise child_exception_type(errno_num, err_msg, err_filename) PermissionError: [Errno 13] Permission denied: './prober/foo' [end of output] note: This error originates from a subprocess, and is likely not a problem with pip. error: metadata-generation-failed × Encountered error while generating package metadata. ╰─> See above for output. note: This is an issue with the package mentioned above, not pip. hint: See above for details.`

**Comment by bilguun0203** [comment]
Found a (cleaner) workaround to the `sysv_ipc` permission denied problem. The `/tmp` directory is mounted with the `noexec` option on HAOS, so it cannot be used for compiling ([ref comment](https://github.com/home-assistant/core/issues/118717#issuecomment-2148826759)). To see the workaround, see the fourth step below.

---

**Here are the complete steps for the workaround:**

1. Access the HAOS shell using one of the following methods:
  - [SSH into HAOS](https://developers.home-assistant.io/docs/operating-system/debugging/)
  - Install & start the [Advanced Terminal & SSH](https://addons.community/#advanced-ssh-web-terminal) add-on with protection mode disabled.
2. Access HA container shell `docker exec -it homeassistant bash`.
2. Install build dependencies `apk add build-base`.
3. Create a new /tmp directory (tmpfs).
```
apk add e2fsprogs
fallocate -l 1G /usr/tmp-disk
mkfs.ext4 /usr/tmp-disk
mount -o loop -t ext4 /usr/tmp-disk /tmp
```
4. Restart Home Assistant.

Note: If you are using Raspberry Pi and the installation was successful, but failed to read the temperature, try adding `use_pulseio=False` parameter to the initialization of the DHT sensor in [sensor.py at line 191](https://github.com/bilguun0203/homeassistant-dht/commit/eed5ddf55405abce271bf09b697ad600c06aa2fd#diff-28663e7f53a05342e575e0f78d8521877460051e41b6aac47f81df544a0c343fL191-R191).

**Comment by stegno** [comment]
> 4. Restart Home Assistant.

Unfortunately still no data from sensors.

**Comment by stegno** [comment]
Issue still not resolved..

**Comment by stegno** [comment]
issue still not resolved :-(

**Comment by Iakovosv** [comment]
Same problem here. will there be any solution? it's been months with the problem

**Comment by DanieleNeo** [comment]
But is there any hope that this problem will be solved (if it is considered a problem) or do I have to transfer my DHT sensors to an EspHome solution?

**Comment by Iakovosv** [comment]
unfortunately the problem remains even after the ha update to 2024.10.2. As an error I get Configuration warnings Platform error 'sensor' from integration 'dht' - Requirements for dht not found: ['adafruit-circuitpython-dht==3.7.0'].
It is not convenient for me in the specific case to put esp since I have the rpi4 I tried to manually install the library but could not. Is something happening with an integration update?
   Στις Σάββατο 12 Οκτωβρίου 2024 στις 02:56:18 μ.μ. EEST, ο χρήστης DanieleNeo ***@***.***> έγραψε:  
 
 


But is there any hope that this problem will be solved (if it is considered a problem) or do I have to transfer my DHT sensors to an EspHome solution?

**Comment by Iakovosv** [comment]
issue still not resolved

**Comment by Iakovosv** [comment]
will there be a solution or should I stop doing it?

**Comment by RPatriziDesign** [comment]
It is just a microcontroller (raspberry pi) and just a pin, it must work! If I am right in understanding the issue, the IO library is not still compatible with the rest of the environment; however, an official upgrade of the adafruit library probably won't be officially available since reading one wire devices is a consuming task for the system. I am too busy at this time but I will try to do something before the end of Christmas hollyday if no one will fix the issue in the meantime... I can't assure you anithing...

**Comment by stegno** [comment]
> I am too busy at this time but I will try to do something before the end of Christmas hollyday if no one will fix the issue in the meantime... I can't assure you anithing...

Thank you, that would be wonderful!

**Comment by ngoclongbkit** [comment]
what's new?

**Comment by Iakovosv** [comment]
No change. it still doesn't work

**Comment by ngoclongbkit** [comment]
please help i need this function

**Comment by stegno** [comment]
up

**Comment by ngoclongbkit** [comment]
Today I updated all the latest changes and tried running again.
Home assistant reported an error:
**Platform error 'sensor' from integration 'dht' - Requirements for dht not found: ['adafruit-circuitpython-dht==3.7.0'].**
Please reopen the bug for support
